INSERT INTO UNIVERSE (UNIVERSE_NAME) VALUES ('MCU');
INSERT INTO UNIVERSE (UNIVERSE_NAME) VALUES ('DC');

INSERT INTO HERO (PERSONAL_NAME, HERO_NAME, UNIVERSE_ID) VALUES ('Tony Stark', 'Iron Man', 1);
INSERT INTO HERO (PERSONAL_NAME, HERO_NAME, UNIVERSE_ID) VALUES ('Bruce Banner', 'Hulk', 1);
INSERT INTO HERO (PERSONAL_NAME, HERO_NAME, UNIVERSE_ID) VALUES ('Bruce Wayne', 'Batman', 2);
INSERT INTO HERO (PERSONAL_NAME, HERO_NAME, UNIVERSE_ID) VALUES ('Clark Kent', 'Superman', 2);
INSERT INTO HERO (PERSONAL_NAME, HERO_NAME, UNIVERSE_ID) VALUES ('Steve Rogers', 'Captain America', 1);
INSERT INTO HERO (PERSONAL_NAME, HERO_NAME, UNIVERSE_ID) VALUES ('Carol Danvers', 'Captain Marvel', 1);
INSERT INTO HERO (PERSONAL_NAME, HERO_NAME, UNIVERSE_ID) VALUES ('Scott Lang', 'Ant Man', 1);
INSERT INTO HERO (PERSONAL_NAME, HERO_NAME, UNIVERSE_ID) VALUES ('TChalla', 'Black Panther', 1);
INSERT INTO HERO (PERSONAL_NAME, HERO_NAME, UNIVERSE_ID) VALUES ('Stephen Strange', 'Doctor Strange', 1);

INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Iron Man', 1);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Iron Man 2', 1);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Iron Man 3', 1);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('The Incredible Hulk', 2);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Captain America: The First Avenger', 5);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Captain America: The Winter Soldier', 5);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Captain America: Civil War', 5);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Captain Marvel', 6);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Ant-Man', 7);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Ant-Man and the Wasp', 7);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Black Panther', 8);
INSERT INTO MOVIE (MOVIE_NAME, HERO_ID) VALUES ('Doctor Strange', 9);
